services:
  django:
    image: mydjango
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

    network_mode: host

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "home"
      POSTGRES_USER: "home"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U home -d home"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"

volumes:
  postgres_data:
